### ISSUE TITLE
Assisted upgrade of fs-extra available

### ISSUE THREAD

**Issue by jsfix-updater** [pregalaxyer/nemo#39]
Version 10 of fs-extra is available.
  The JSFIX tool can help you through the update process (**Ensuring that all the necessary changes are made to your project in the process**).
  Use this [link](https://jsfix.live/jsfix/https%3A%2F%2Fgithub.com%2Fpregalaxyer%2Fnemo) to start the upgrade process (_It's completely free_).
  
  Leave a comment on this issue if you have any questions or concerns.

**Comment by diveDylan** [comment]
@jsfix-updater can you create a pr for this

**Comment by mtorp** [comment]
Hi @diveDylan,

Sure. I've opened a PR for you https://github.com/pregalaxyer/nemo/pull/40
