### ISSUE TITLE
support for json input

### ISSUE THREAD

**Issue by diveDylan** [pregalaxyer/nemo#4]

**Comment by diveDylan** [comment]
@kamdai  @Kujo-Jotaro-AAAAA  扩展直接输入 `json` 或者 `json ` 文件，不是单一的 `swagger api json` 地址

**Comment by gary-fei** [comment]
what

**Comment by diveDylan** [comment]
简单描述一下：
1. 你需要支持直接输入 `.json` 文件 或者 `json` 数据
2. 需要支持检查核心几个 `json` 属性，比如: `tag`, `path`, `definition` 等
